import { Finding, SEVERITY_ORDER, Severity } from "../engine/types";

export interface ReportInput {
  targetLabel: string;
  startedAt: string;
  pgVersion: string;
  findings: Finding[];
  comparedToRunId?: number | null;
}

function severityIcon(sev: Severity): string {
  switch (sev) {
    case "critical":
      return "🔴";
    case "high":
      return "🟠";
    case "medium":
      return "🟡";
    case "low":
      return "🔵";
    case "info":
      return "⚪";
  }
}

export function renderReport(input: ReportInput): string {
  const { targetLabel, startedAt, pgVersion, findings } = input;

  const counts = Object.fromEntries(
    SEVERITY_ORDER.map((s) => [s, findings.filter((f) => f.severity === s).length])
  ) as Record<Severity, number>;

  const lines: string[] = [];
  lines.push(`# Security Audit Report — ${targetLabel}`);
  lines.push("");
  lines.push(`- **Started:** ${startedAt}`);
  lines.push(`- **Server:** ${pgVersion.split(" on ")[0]}`);
  if (input.comparedToRunId != null) {
    lines.push(`- **Drift compared against run:** #${input.comparedToRunId}`);
  }
  lines.push(
    `- **Findings:** ${counts.critical} critical · ${counts.high} high · ${counts.medium} medium · ${counts.low} low · ${counts.info} info`
  );
  lines.push("");
  lines.push("> ⚠️ This report maps the weaknesses of the audited target. Treat it as confidential.");
  lines.push("");

  let total = 0;
  for (const sev of SEVERITY_ORDER) {
    const group = findings
      .filter((f) => f.severity === sev)
      .sort((a, b) => a.id.localeCompare(b.id));
    if (group.length === 0) continue;
    total += group.length;

    lines.push(`## ${severityIcon(sev)} ${sev.toUpperCase()} (${group.length})`);
    lines.push("");
    for (const f of group) {
      lines.push(`### ${f.title}`);
      lines.push("");
      lines.push(`- **ID:** \`${f.id}\``);
      lines.push(`- **Category:** ${f.category}`);
      lines.push("");
      lines.push(f.description);
      lines.push("");
      lines.push("**Evidence**");
      lines.push("");
      lines.push("```json");
      lines.push(JSON.stringify(f.evidence, null, 2));
      lines.push("```");
      lines.push("");
      lines.push(`**Recommendation:** ${f.recommendation}`);
      lines.push("");
    }
  }

  if (total === 0) {
    lines.push("## ✅ No findings");
    lines.push("");
    lines.push("No issues were detected by the v1 rule set. Keep in mind this is a passive check, not a guarantee of security.");
    lines.push("");
  }

  lines.push("---");
  lines.push(
    `Generated by sol-db v1 at ${new Date().toISOString()}. Passive introspection only — no table data was read.`
  );
  lines.push("");

  return lines.join("\n");
}

export function reportFileName(targetLabel: string, startedAt: string): string {
  const stamp = startedAt.replace(/[:.]/g, "-").slice(0, 19);
  return `${targetLabel}-${stamp}.md`;
}
